### ISSUE TITLE
Specify environment

### ISSUE THREAD

**Issue by hazcod** [unacast/actions-github-deployment-status#5]
Hi,
Is it possible to specify the deployment environment?

**Comment by judoole** [comment]
Hi @hazcod! I should believe that this is supplied from the request that created the deployment event.

For example if you fired off your deployment via the Github Slack plugin, like this https://github.blog/2019-07-29-whats-new-in-the-github-and-slack-integration/, then your environment is supplied by yourself. 

You can reuse this inside your Github Actions, in any way you would like, for example like so:

```
- name: Deploy to my environment
        env:
          DEPLOY_ENVIRONMENTY: ${{ github.event.deployment.environment }}
        run: ./scripts/my-deploy-script.sh
```

That is independent of this action though, and a standard Github Actions way of doing things . This action is a helper for updating the Github API when things are done, started or failure/error.

I'll make a note of updating the documentation, so that this seems more clear.
