### ISSUE TITLE
Unprocessable Entity responses

### ISSUE THREAD

**Issue by cescoffier** [unacast/actions-github-deployment-status#6]
First, thanks for your action, it was the missing piece in my deployment pipeline. 

I might be an issue with the GitHub API, but just in case, I'm seeing 422 - Unprocessable Entity responses:

```
Run unacast/actions-github-deployment-status@0.2
  with:
    github_token: ***
    status: Success%
/usr/bin/docker run --name ee6219631a1d3344f6188cab6ca6c0ad43c_a5d464 --label 671ee6 --workdir /github/workspace --rm -e INPUT_GITHUB_TOKEN -e INPUT_STATUS -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/quarkus-images/quarkus-images":"/github/workspace" 671ee6:219631a1d3344f6188cab6ca6c0ad43c  "Success%"
Setting status to success% for deployment-id '192234251'
Connecting to api.github.com (140.82.113.6:443)
wget: server returned error: HTTP/1.1 422 Unprocessable Entity
```

The configuration is very basic:

```
- name: update deploy status
        if: always()
        uses: unacast/actions-github-deployment-status@0.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}%          
```
